### ISSUE TITLE
 Error in `/var/packages/AirConnect/target/airupnp': free(): invalid pointer: 0x7101fb60

### ISSUE THREAD

**Issue by looching** [philippe44/AirConnect#135] opened 2019-01-08 14:50 UTC
hi I've install your package on my ds216play (Monaco).
I run it but I fail to see any airplay source on my iphone.
I checked the log and here was what I got:

```
[22:39:37.301526] MasterHandler:606 [0x95fc8]: subscribe fail, re-trying 3
[22:39:37.306107] MasterHandler:610 [0x95fc8]: subscribe fail, volume feedback will not work
[22:39:37.561508] AddMRDevice:896 [0x97eec]: adding renderer (土豆大屏幕)
[22:39:37.575331] MasterHandler:604 [0x97eec]: subscribe success
[22:39:37.804010] AddMRDevice:896 [0x99e10]: adding renderer (卧室)
[22:39:37.809941] MasterHandler:604 [0x99e10]: subscribe success
[22:39:37.826576] ProcessEvent:403 [0x99e10]: UPnP Volume local change 25
[22:39:39.335771] AddMRDevice:896 [0x9bd34]: adding renderer (搜狐TV播放器 192.168.2.132)
[22:39:39.349565] MasterHandler:604 [0x9bd34]: subscribe success
*** Error in `/var/packages/AirConnect/target/airupnp': free(): invalid pointer: 0x7101fb60 ***
```

it seems some error occurred but I can't find any solution related to it.
Could you plz tell me what was wrong or any clue on solving it ?

**Comment by philippe44** [comment] 2019-01-09 18:41
Can you try to run it first on a classical computer like a PC Linux, Windows or a Pi? I want to know if the issue is related to the DS216 or the name of your players (unicode problem)

**Comment by looching** [comment] 2019-01-11 06:08
i've tried running the windows system version，it worked but those names were not displaying properly. So I think it is not a unicode problem. let me try to reinstall on ds216 or find a Pi to rerun it.

**Comment by looching** [comment] 2019-01-11 17:33
tried to clone the repo and rerun it on ds216, got same result 

```
root@ChingNAS:~/AirConnect/bin# ./airupnp-arm -l 1000:2000
[01:30:13.577023] main:1224 Starting airupnp version: v0.2.2.4 (Dec 16 2018 @ 16:04:27)
[01:30:13.577550] main:1232 no config file, using defaults
[01:30:13.629034] Start:984 Binding to 192.168.2.49:49152
[01:30:13.807402] AddMRDevice:896 [0x941b4]: adding renderer (CIBN酷喵影视_AFTB)
[01:30:13.871329] MasterHandler:604 [0x941b4]: subscribe success
[01:30:13.873012] AddMRDevice:896 [0x960d8]: adding renderer (斗鱼(828))
[01:30:13.881210] MasterHandler:604 [0x960d8]: subscribe success
[01:30:13.889894] ProcessEvent:403 [0x960d8]: UPnP Volume local change 100
[01:30:13.895928] XMLGetFirstDocumentItem:1326 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
[01:30:13.986576] AddMRDevice:896 [0x97ffc]: adding renderer (卧室)
[01:30:13.991697] MasterHandler:604 [0x97ffc]: subscribe success
[01:30:14.010533] ProcessEvent:403 [0x97ffc]: UPnP Volume local change 25
*** Error in `./airupnp-arm': free(): invalid pointer: 0x72813710 ***
Aborted (core dumped)

**Comment by looching** [comment] 2019-01-12 14:33
I ran it on a Pi and got the same result:

```
root@raspberrypi:~/AirConnect/bin# ./airupnp-arm -l 1000:2000
[22:30:35.892071] main:1224 Starting airupnp version: v0.2.2.4 (Dec 16 2018 @ 16:04:27)
[22:30:35.892546] main:1232 no config file, using defaults
[22:30:35.895455] Start:984 Binding to 192.168.2.95:49152
[22:30:36.231792] AddMRDevice:896 [0x941b4]: adding renderer (卧室)
[22:30:36.237921] MasterHandler:604 [0x941b4]: subscribe success
[22:30:36.252168] AddMRDevice:896 [0x960d8]: adding renderer (CIBN酷喵影视_AFTB)
[22:30:36.255111] ProcessEvent:403 [0x941b4]: UPnP Volume local change 25
[22:30:36.290641] MasterHandler:604 [0x960d8]: subscribe success
[22:30:36.295733] XMLGetFirstDocumentItem:1326 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
[22:30:36.465921] AddMRDevice:896 [0x97ffc]: adding renderer (土豆大屏幕)
[22:30:36.486806] MasterHandler:604 [0x97ffc]: subscribe success
[22:30:36.494561] XMLGetFirstDocumentItem:1326 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
[22:30:37.288684] AddMRDevice:896 [0x99f20]: adding renderer (斗鱼(828))
[22:30:37.297743] MasterHandler:604 [0x99f20]: subscribe success
[22:30:37.303837] ProcessEvent:403 [0x99f20]: UPnP Volume local change 100
[22:30:41.052255] AddMRDevice:896 [0x9be44]: adding renderer (优酷XL (192.168.2.143))
[22:30:42.788191] AddMRDevice:896 [0x9dd68]: adding renderer (搜狐TV播放器 192.168.2.143)
[22:30:42.825730] MasterHandler:604 [0x9dd68]: subscribe success
[22:30:42.839616] XMLGetFirstDocumentItem:1326 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
*** Error in `./airupnp-arm': free(): invalid pointer: 0x70f0d3f8 ***
```

it seems the arm version is not working on my machine

**Comment by philippe44** [comment] 2019-01-13 06:33
If you also have a problem on the Pi, it's likely a multichar player name problem. Can you give it a different name

**Comment by looching** [comment] 2019-01-13 14:01
Thank you and no, I can't change all the names. I'll try your new version and see how to get you some hints with gdb

**Comment by looching** [comment] 2019-01-13 14:18
I just ran you new version and it works on my Pi. I didn't try gdb. Do you still need it ?

**Comment by looching** [comment] 2019-01-14 15:47
Sorry I somehow broke my Pi and can't get log out of it. I'll post log here later when I fix it.

**Comment by philippe44** [comment] 2019-01-30 05:21
I'll close the issue - feel free to re-open if needed

**Closed by philippe44** 2019-01-30 05:21 UTC

**Comment by huzheyi** [comment] 2020-07-06 07:32
I've got a same problem as this topic.
I ran airconnect perfectly on my windows PC, while it threw an error on my amlogic device running Volumio.
The dropbox link you provided before is now out of date, could you please upload a new one ?

```
root@volumio:~# ./airupnp-arm
[07:22:15.108967] main:1378 Starting airupnp version: v0.2.26.1 (May 27 2020 @ 19:06:08)
[07:22:15.109239] main:1386 no config file, using defaults
[07:22:15.160417] Start:1103 Binding to 192.168.1.142:49153
[07:22:15.527207] AddMRDevice:991 [0x974d0]: adding renderer (CIBN酷喵_客厅)
[07:22:15.527565] AddMRDevice:1012 [0x974d0]: cannot get mac CIBN酷喵_客厅+, creating fake 1ace8b8d
[07:22:15.587492] MasterHandler:655 [0x974d0]: subscribe success
[07:22:15.645698] AddMRDevice:991 [0x99910]: adding renderer (浴室)
[07:22:15.645842] AddMRDevice:1012 [0x99910]: cannot get mac 浴室+, creating fake 73b28a4
[07:22:15.660007] XMLGetFirstDocumentItem:1390 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
[07:22:15.665621] MasterHandler:655 [0x99910]: subscribe success
[07:22:15.739150] AddMRDevice:991 [0x9bd50]: adding renderer (厨房)
[07:22:15.739294] AddMRDevice:1012 [0x9bd50]: cannot get mac 厨房+, creating fake 9d03ee72
[07:22:15.753537] MasterHandler:655 [0x9bd50]: subscribe success
*** Error in `./airupnp-arm': free(): invalid pointer: 0xf160f528 ***
Aborted
```
