### ISSUE TITLE
Audio never restarts if AirConnect is restarted when iPhone is playing

### ISSUE THREAD

**Issue by eric** [philippe44/AirConnect#47] opened 2018-02-02 20:46 UTC
I've noticed a strange behavior around restarts that continues on v0.2.0.2.

### Steps to reproduce:

1. Stream from an iPhone to a Sonos speaker via AirConnect
2. Hit "pause" on the iPhone
3. Restart AirConnect
4. Observe that the iPhone still is waiting to stream to the Sonos
5. Hit "play" on the iPhone

### Expected:

Audio eventually starts to play

### Actual:

Silence

**Comment by philippe44** [comment] 2018-02-03 08:28
It probably depends how you stop AirConnect. it normally broadcasts (when terminated gracefully) that players are being removed. Having said that, not all controllers handle that "removal while they are controlling a device" very well - candily, it's an extreme corner case you're describing here. AirConnect is intended to always run on the background. I also assume that if you un-select that player are re-select it on the iPhone it will work again

**Comment by eric** [comment] 2018-02-03 08:30
It’s true that deselecting and reselecting does solve the problem. From the logs it does appear that the iPhone does start streaming to the new device but it doesn’t seem to ever start playing on the Sonos.

**Comment by philippe44** [comment] 2018-02-08 05:33
If you don't mind, I'd like to close the issue. I know approximatively where the problem is, but that's a lot of searches and potential changes for a very corner case that can easily be solved by a simple user action if you ever had a paused iOS devices when you stopped/restarted AirConnect.

**Comment by eric** [comment] 2018-02-14 04:55
I've heard of other people having 👻 spooky 👻 issues with streaming stopping after a while and not starting again until the AirPlay settings have been toggled back to iPhone and back. I'm not sure if it's related to this or if it's separate, but it did make me wonder.

If this wouldn't help other sorts of issues like that, I'd be fine closing this.

**Comment by philippe44** [comment] 2018-02-16 00:20
I corrected a few minor things in 0.2.0.3, let's see if it solves this as well

**Comment by eric** [comment] 2018-02-16 00:24
Great! I’ll check it out.

**Closed** 2018-03-07 04:17 UTC
